name: Update Ecodia Vectors

on:
  workflow_dispatch:      # Manual trigger
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC (adjust as needed)

jobs:
  update-vectors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full repo history needed for push

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update soul_with_vectors.json
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      run: |
        python update_Vectors.py

    - name: "Debug: Show current Git remote URL"
      run: git remote get-url origin

    - name: Remove GitHub token header to avoid override
      run: |
        git config --unset http.https://github.com/.extraheader || echo "No extraheader set"

    - name: Commit and push if changed
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add soul_with_vectors.json
        git diff --cached --quiet || git commit -m "Automated update: regenerate vectors"
        # Set remote URL with PAT token for authentication
        git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
        git push origin HEAD:${{ github.ref }}
